- Directory.Packages.props
- src/RadixDlt.NetworkGateway.GatewayApi/CoreCommunications/CoreApiHandler.cs
- src/RadixDlt.NetworkGateway.GatewayApi/Services/IPreviewService.cs
- src/RadixDlt.NetworkGateway.GatewayApi/Services/ISubmissionServiceObserver.cs
- src/RadixDlt.NetworkGateway.GatewayApi/Services/ISubmissionTrackingService.cs
- src/RadixDlt.NetworkGateway.GatewayApi/Services/SubmissionService.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/Services/SubmissionTrackingService.cs
- src/RadixDlt.NetworkGateway.PrometheusIntegration/GatewayApiMetricObserver.cs
Reverts radixdlt/babylon-gateway#120
> Revert "Use radix engine toolkit library to statically validate transaction"

- .github/workflows/releases.yml
Store Dockerhub credentials in AWS
This is analog to babylon-node and babylon-nginx
> DO-1167-fetch docker credentials from aws

- src/RadixDlt.NetworkGateway.PostgresIntegration/Services/EntityStateQuerier.cs
> fix returning data for virtual accounts and virtual

- CHANGELOG.md
- src/RadixDlt.NetworkGateway.PostgresIntegration/LedgerExtension/PostgresLedgerExtenderService.cs
- fixed access rules double json serialization.
> add missing changelog entries, fix access rules chain

- .editorconfig
- src/RadixDlt.NetworkGateway.Abstractions/Extensions/DateTimeExtensions.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/RadixDlt.NetworkGateway.PostgresIntegration.csproj
- src/RadixDlt.NetworkGateway.PostgresIntegration/ScryptoSborUtils.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/Services/EntityStateQuerier.cs
Uses C#11 features (list patterns) which should be compatible with Gateway build 🤞
> fix: Add string representations for all metadata values

- .github/workflows/main.yml
Trigger GW benchmarking tests on push to develop
> updated condition for triggering GW benchmark test

- .github/workflows/releases.yml
- Change upload_url variable on Upload DataAggreagtor zip
> ci: fix upload artifact data aggregator

- apps/GatewayApi/Controllers/StateNonFungibleController.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/LedgerExtension/PostgresLedgerExtenderService.cs
- access controller
- account
- pools
> store and return state for

- sdk/typescript/README.md
- describe `applicationName` parameter
- Change order of sections - "high level apis" go first, then "low level apis"
> docs: update readme

- sdk/typescript/lib/helpers/networks.ts
This reverts commit bfc2df3105fa07f7a62fc00d59c02fab7ca38bac.
> Revert "fix: mainnet gateway url"

- sdk/typescript/README.md
- sdk/typescript/lib/constants.ts
- sdk/typescript/lib/index.ts
- sdk/typescript/lib/runtime.ts
- sdk/typescript/lib/subapis/state.ts
- sdk/typescript/lib/subapis/statistics.ts
* add high level wrappers 
* exhaust fungibles pagination when calling `getEntityDetailsVaultAggregated`
> Improvements

- CHANGELOG.md
- src/RadixDlt.NetworkGateway.PostgresIntegration/LedgerExtension/PostgresLedgerExtenderService.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/LedgerExtension/WriteHelper.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/Models/LedgerTransaction.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/Services/CommittedStateIdentifiersReader.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/Services/TopOfLedgerProvider.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/Services/TransactionQuerier.cs
TODO:
- Add changelog update once version bump gets committed to `develop`.
> Optimized TransactionQuerier.GetTransactions not to fetch unnecessary data from database

- CHANGELOG.md
- src/RadixDlt.NetworkGateway.GatewayApi/gateway-api-schema.yaml
- src/RadixDlt.NetworkGateway.GatewayApiSdk/generated/Model/StateEntityDetailsResponseFungibleVaultDetailsAllOf.cs
- src/RadixDlt.NetworkGateway.GatewayApiSdk/generated/Model/StateEntityDetailsResponseNonFungibleVaultDetails.cs
- src/RadixDlt.NetworkGateway.GatewayApiSdk/generated/Model/StateEntityDetailsResponseNonFungibleVaultDetailsAllOf.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/Services/EntityStateQuerier.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/Services/EntityStateQuerier.fungibles.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/Services/EntityStateQuerier.nonfungibles.cs
Request:
```
{
"addresses": [
"internal_vault_loc1npgugk3kynezldysah80y8mu9uxgnf8zw4qsdrpj83vefx98fum52x",
"internal_vault_loc1tpgd53d5cmusz3qnk0sx4nfk20w2npy3vfpryas527klls74jelpc9"
],
"opt_ins":{
"non_fungible_include_nfids": true
}
}
```
Response fragment:
```
"items": [
{
"address": "internal_vault_loc1tpgd53d5cmusz3qnk0sx4nfk20w2npy3vfpryas527klls74jelpc9",
"metadata": {
"total_count": 0,
"items": []
},
"details": {
"balance": {
"vault_address": "internal_vault_loc1tpgd53d5cmusz3qnk0sx4nfk20w2npy3vfpryas527klls74jelpc9",
"amount": "485.144557082581734652",
"last_updated_at_state_version": 18
},
"type": "FungibleVault"
}
},
{
"address": "internal_vault_loc1npgugk3kynezldysah80y8mu9uxgnf8zw4qsdrpj83vefx98fum52x",
"metadata": {
"total_count": 0,
"items": []
},
"details": {
"balance": { …
```
> Added vault-related details to lookups in /state/entity/details endpoint.

- src/RadixDlt.NetworkGateway.GatewayApi/gateway-api-schema.yaml
- /state/entity/details
- /state/key-value-store/data
- /state/non-fungible/location
- /state/non-fungible/data
endpoints.
> add information about max items limit in:

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- babylon-gateway.sln
we keep tests in separate repository (test-harness) so it'd make sense to point ppl there and ask them to verify/write new tests and also regenerate client if they add any changes.
> added CONTRIBUTING.md and CODE_OF_CONDUCT.md files.

- CHANGELOG.md
- src/RadixDlt.NetworkGateway.GatewayApi/gateway-api-schema.yaml
- src/RadixDlt.NetworkGateway.GatewayApiSdk/generated/Model/StateNonFungibleLocationResponseItem.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/Services/EntityStateQuerier.cs
- src/RadixDlt.NetworkGateway.PostgresIntegration/Services/EntityStateQuerier.nonfungibles.cs
> NFID vault ancestor addresses

- CHANGELOG.md
- src/RadixDlt.NetworkGateway.Abstractions/Model/LedgerTransactionEventFilter.cs
- src/RadixDlt.NetworkGateway.GatewayApi/Configuration/EndpointOptions.cs
- src/RadixDlt.NetworkGateway.GatewayApi/Validators/StreamTransactionsRequestValidator.cs
- src/RadixDlt.NetworkGateway.GatewayApi/gateway-api-schema.yaml
- src/RadixDlt.NetworkGateway.GatewayApiSdk/Model/StreamTransactionsRequest.cs
- tests/RadixDlt.NetworkGateway.UnitTests/GatewayApiSdk/Model/StreamTransactionsRequestTests.cs
Sample error response:
```
{
"message": "One or more validation errors occurred",
"code": 400,
"details": {
"validation_errors": [
{
"path": "",
"errors": [
"The overall number of filters applied (27) must be less than or equal to 10."
]
}
],
"type": "InvalidRequestError"
},
"trace_id": "00-3de55d2d74091555ddae8e732547f74b-05e01dd7e3ee6312-00"
}
```
> Stream filters limit

- sdk/typescript/README.md
> docs: update `Babylon Gateway API` link

- .github/workflows/main.yml
2 more env vars are needed to get the slack notification working properly
> Add more missing GitHub action environment variables

- .github/workflows/main.yml
Disable mardunet deployment when pushing to develop
> ci: Disable mardunet deployment

- sdk/typescript/lib/subapis/state.ts
- sdk/typescript/test/state.test.ts
Add `dappTwoWayLinks` and `nativeResourceDetails` opt-ins to state high level api
> fix: add `dappTwoWayLinks` and `nativeResourceDetails` opt-ins to state high level api

- sdk/typescript/lib/subapis/transaction.ts
> [!IMPORTANT]
>
> * Please read our [Contributing Guidelines](https://github.com/radixdlt/babylon-gateway/blob/main/CONTRIBUTING.md) before opening a PR.
> * Before creating your PR, please ensure you have used the _correct base branch_ as per the [branching strategy](https://github.com/radixdlt/babylon-gateway/blob/main/docs/branching-strategy.md), both for branching from, and in the PR UI above.
>   * For most code changes, this is `develop`.
>   * For stand-alone docs changes, this is `main`.
>   * For changes that should be included in the pending release, this is `release/*` branch. 
> * Please remove these sections as you fill out your PR.
> 
> [!TIP]
> 
> Start with the context of your PR. Why are you making this change? What does it address? Link back to an issue if relevant.
> …
> add manifest instruction opt in

- CHANGELOG.md
Briefly explained the main toolkit changes in the CHANGELOG.
N/A
> docs: Mention the toolkit classification update in the CHANGELOG
